apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lnl60a0ye-python 
  janus-idp.io/tekton: lnl60a0ye-python
  backstage.io/kubernetes-id: lnl60a0ye-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lnl60a0ye-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  