apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lnl60a0ye-python
  janus-idp.io/tekton: lnl60a0ye-python
  backstage.io/kubernetes-id: lnl60a0ye-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lnl60a0ye-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
