apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lnl60a0ye-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:beba102d050b1564fcf837dcde660f9bedfc7d6e@sha256:e6f1ab60cdf48e6224fe8ca9ded5a1f8c0e462b3d06e208b1b48ebe79868b7fb
          name: container-image
